import "~/styles/globals.css";

// Mantine core styles
import '@mantine/core/styles.css';
import {MantineProvider} from "@mantine/core";

import {GeistSans} from "geist/font/sans";
import {type Metadata} from "next";
import {Providers} from "~/app/providers";


export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className={GeistSans.className}>
        <MantineProvider>
            <Providers>
                {children}
            </Providers>
        </MantineProvider>
        </body>
        </html>
    );
}
